### ISSUE TITLE
Consider add block height into /account/balance request/response

### ISSUE THREAD

**Issue by raullenchai** [coinbase/rosetta-specifications#16]
**Is your feature request related to a problem? Please describe.**
Without block height, the returned balance does not make sense.

**Describe the solution you'd like**
add block height into /account/balance request/response, e.g., https://www.rosetta-api.org/docs/AccountApi.html

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-ogrady** [comment]
👋  @raullenchai The `/account/balance` [request](https://www.rosetta-api.org/docs/models/AccountBalanceRequest.html) already allows the client to optionally specify a block height to look up a balance (if it is not provided, it is assumed to be a balance lookup at the last block synced by the node).

The `/account/balance` [response](https://www.rosetta-api.org/docs/models/AccountBalanceResponse.html) already returns the block height (and associated block hash) at which the balance was calculated.

Since this functionality already exists in the specification, I'm going to close this issue.

**Comment by raullenchai** [comment]
Thanks for the clarificaiton

**Comment by patrick-ogrady** [comment]
If you have any questions while working on an implementation, feel free to reach out [here](https://community.rosetta-api.org/)!
